export const INIT_THREE = 'INIT_THREE';
export const INIT_PROCEDURIA = 'INIT_PROCEDURIA';
export const LOAD_RULES = 'LOAD_RULES';
export const GENERATE_POSITIONS = 'GENERATE_POSITIONS';
export const GENERATE_DATA_FROM_RULE_FOR_EACH_POSITION = 'GENERATE_DATA_FROM_RULE_FOR_EACH_POSITION';
export const GENERATE_DATA = 'GENERATE_DATA';
export const RULE_0 = 'RULE_0';

export const CAMERA_TYPE_ORBITAL = 'CAMERA_TYPE_ORBITAL';
export const CAMERA_TYPE_FPS = 'CAMERA_TYPE_FPS';
