export const initialState = {
  camera: null,
  cameraAutoRotate: false,
  cameracontrols: null,
  cameraType: "orbit",
  canvas: null,
  ctx: null,
  debug: true,
  dev: true,
  delta: -1,
  faces: [],
  far: 1000,
  fov: 75,
  height: 240,
  near: 0.001,
  objects: [],
  ratio: -1,
  renderer: null,
  scene: null,
  seed: "proc.edu.ria",
  size: 4,
  shadows: false,
  vertices: [],
  width: 320,
  wireframe: false,
  zoom: 1,
};
