export const initialState = {
  camera: null,
  cameraAutoRotate: false,
  cameraAutoRotateAngle: 0.25,
  cameraControls: null,
  cameraType: "orbit",
  cubicSize: -1,
  debug: true,
  // delta: -1,
  // elasped: -1,
  // faces: [],
  far: 1000,
  fov: 75,
  // geometry: null,
  hash: null,
  hashRange: [],
  height: 360,
  // mesh: {},
  // material: {},
  near: 0.001,
  // objects: [],
  positions: [],
  ratio: -1,
  rules: {},
  renderer: null,
  scene: null,
  seed: "proc.edu.ria",
  shadows: false,
  size: 4,
  squareSize: -1,
  // sun: {
  //   angle: 0,
  // },
  // time: {
  //   hours: 0,
  //   minutes: 0,
  //   seconds: 0,
  // },
  // timeScale: 1,
  // vertices: [],
  width: 640,
  wireframe: false,
  zoom: 1,
};
